/**
 * Design System Variables
 * 
 * This file is auto-generated from variables.json
 * Do not edit this file directly - edit variables.json instead
 * and run "npm run build:variables" to regenerate.
 */

export const variables = {
  // Breakpoints (in pixels)
  breakpoints: {
    s: 759,
    m: 910,
    l: 1104,
    xl: 1408,
  },

  // Layout
  layout: {
    gridGutter: '1rem',
    cornerRadius: '2px',
    buttonRadius: '4px',
  },

  // Colors
  colors: {
    whiteSoft: 'rgb(253, 253, 253)',
    whiteSoftTransparent: 'rgba(253, 253, 253, .5)',
    blackSoft: 'rgb(14, 14, 14)',
    blackSoftTransparent: 'rgba(14, 14, 14, .5)',
    red: '#FF1941',
    acfmPink: '#FC16CB',
    yellow: '#EBB800',
    green: '#5FCC00',
    greenNeon: '#CADB2A',
    greenRacing: '#55846B',
    blue: 'rgb(84, 144, 235)',
    blueNeon: '#0018F0',
    blueLight: '#CAE5FF',
    teal: '#E3FFFF',
    lilac: '#B1B1FF',
    gray: 'rgb(150,150,150)',
    grayTransparent: 'rgba(150,150,150, .5)',
    grayLight: 'rgb(190,190,190)',
    grayLightTransparent: 'rgba(190,190,190, .5)',
    grayExtraLight: '#EDEAEA',
  },

  // Transitions (in milliseconds)
  transitions: {
    speedSlow: 1111,
    speedMedium: 420,
    speedQuick: 140,
    speedUltra: 33,
  },

  // Constants
  constants: {
    goldenRatio: 1.61803398875,
  }
};

// CSS Custom Property Names (for use with getComputedStyle, etc.)
export const cssVariableNames = {
  layout: {
    gridGutter: '--grid-gutter',
    cornerRadius: '--corner-radius',
    buttonRadius: '--button-radius',
  },

  colors: {
    whiteSoft: '--color-white-soft',
    whiteSoftTransparent: '--color-white-soft-transparent',
    blackSoft: '--color-black-soft',
    blackSoftTransparent: '--color-black-soft-transparent',
    red: '--color-red',
    acfmPink: '--color-acfm-pink',
    yellow: '--color-yellow',
    green: '--color-green',
    greenNeon: '--color-green-neon',
    greenRacing: '--color-green-racing',
    blue: '--color-blue',
    blueNeon: '--color-blue-neon',
    blueLight: '--color-blue-light',
    teal: '--color-teal',
    lilac: '--color-lilac',
    gray: '--color-gray',
    grayTransparent: '--color-gray-transparent',
    grayLight: '--color-gray-light',
    grayLightTransparent: '--color-gray-light-transparent',
    grayExtraLight: '--color-gray-extra-light',
  },

  typography: {
    fontFamilySans: '--font-family-sans',
    fontFamilySerif: '--font-family-serif',
  },

  transitions: {
    speedSlow: '--transition-speed-slow',
    speedMedium: '--transition-speed-medium',
    speedQuick: '--transition-speed-quick',
    speedUltra: '--transition-speed-ultra',
  },

  breakpoints: {
    s: '--breakpoint-s',
    m: '--breakpoint-m',
    l: '--breakpoint-l',
    xl: '--breakpoint-xl',
  }
};

// Default export for convenience
export default variables;
