/**
 * Design System Variables
 * 
 * This file is auto-generated from variables.json
 * Do not edit this file directly - edit variables.json instead
 * and run "npm run build:variables" to regenerate.
 */

export const variables = {
  // Breakpoints (in pixels)
  breakpoints: {
    s: 759,
    m: 910,
    l: 1104,
    xl: 1408,
  },

  // Layout
  layout: {
    gridGutter: '1rem',
    cornerRadius: '2px',
    cornerRadiusLarge: '4px',
    buttonRadius: '4px',
  },

  // Colors
  colors: {
    whiteSoft: 'rgb(253, 253, 253)',
    whiteSoftTransparent: 'rgba(253, 253, 253, .5)',
    blackSoft: 'rgb(14, 14, 14)',
    blackSoftTransparent: 'rgba(14, 14, 14, .5)',
    red: '#FF1941',
    acfmPink: '#FF19B4',
    pink: '#FF19B4',
    yellow: '#EBB800',
    green: '#5FCC00',
    greenNeon: '#CADB2A',
    greenRacing: '#55846B',
    blue: 'rgb(84, 144, 235)',
    blueNeon: '#0018F0',
    blueLight: '#CAE5FF',
    teal: '#E3FFFF',
    lilac: '#B1B1FF',
    gray: 'rgb(150,150,150)',
    grayBase: '#f8f5f5',
    grayLightOld: 'rgb(190,190,190)',
    grayLight: '#EDEAEA',
    grayMid: '#D4D4D4',
    grayMidNew: '#D4D4D4',
    red900: '#8C0E24',
    red800: '#B4122E',
    red700: '#D51536',
    red600: '#F2183E',
    red500: '#FF1941',
    red400: '#FF8D96',
    red300: '#FFB5BA',
    red200: '#FFD6D8',
    red100: '#FFE6E7',
  },

  // Transitions (in milliseconds)
  transitions: {
    speedSlow: 1111,
    speedMedium: 420,
    speedQuick: 140,
    speedUltra: 33,
  },

  // Constants
  constants: {
    goldenRatio: 1.61803398875,
  }
};

// CSS Custom Property Names (for use with getComputedStyle, etc.)
export const cssVariableNames = {
  layout: {
    gridGutter: '--grid-gutter',
    cornerRadius: '--corner-radius',
    cornerRadiusLarge: '--corner-radius-large',
    buttonRadius: '--button-radius',
  },

  colors: {
    whiteSoft: '--color-white-soft',
    whiteSoftTransparent: '--color-white-soft-transparent',
    blackSoft: '--color-black-soft',
    blackSoftTransparent: '--color-black-soft-transparent',
    red: '--color-red',
    acfmPink: '--color-acfm-pink',
    pink: '--color-pink',
    yellow: '--color-yellow',
    green: '--color-green',
    greenNeon: '--color-green-neon',
    greenRacing: '--color-green-racing',
    blue: '--color-blue',
    blueNeon: '--color-blue-neon',
    blueLight: '--color-blue-light',
    teal: '--color-teal',
    lilac: '--color-lilac',
    gray: '--color-gray',
    grayBase: '--color-gray-base',
    grayLightOld: '--color-gray-light-old',
    grayLight: '--color-gray-light',
    grayMid: '--color-gray-mid',
    grayMidNew: '--color-gray-mid-new',
    red900: '--color-red-900',
    red800: '--color-red-800',
    red700: '--color-red-700',
    red600: '--color-red-600',
    red500: '--color-red-500',
    red400: '--color-red-400',
    red300: '--color-red-300',
    red200: '--color-red-200',
    red100: '--color-red-100',
  },

  typography: {
    fontFamilySans: '--font-family-sans',
    fontFamilySerif: '--font-family-serif',
  },

  transitions: {
    speedSlow: '--transition-speed-slow',
    speedMedium: '--transition-speed-medium',
    speedQuick: '--transition-speed-quick',
    speedUltra: '--transition-speed-ultra',
  },

  breakpoints: {
    s: '--breakpoint-s',
    m: '--breakpoint-m',
    l: '--breakpoint-l',
    xl: '--breakpoint-xl',
  }
};

// Default export for convenience
export default variables;
